### ISSUE TITLE
Bower gebruiken i.p.v. dit project?

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review-static#2]
Misschien zie ik wat over het hoofd, maar met [Bower](http://bower.io) (package manager) is het super makkelijk om third party javascript en css toe te voegen en te updaten. Namelijk als volgt:

``` js
// ./bower.json
{
  "name": "open-review",
  "directory": "static/components",
  "dependencies": {
    "jquery": "~2.0.3"
    // ...
  }
}
```

`$ bower install`

Hiermee worden packages alle automatisch toegevoegd aan `static/components`. Voordeel is dat je de versies locked, je makkelijk kunt zien welke versies en welke libs er geïnstalleerd zijn, en het heel makkelijk is een nieuwe library toe te voegen. Vervolgens kun je ze includen met script/link tags net als andere assets.

Maar zoals ik al zei, misschien lost dit het probleem niet op want het is me eerlijk gezegd ook ontgaan waarom deze repo precies bestaat.

/cc @WNoort @martijnbastiaan

**Comment by martijnbastiaan** [comment]
Yes, dit lost het probleem op voor jQuery maar nog niet voor de lettertypen - dus ik ben bang dat open-review-static moet blijven bestaan :(.
